Popup window modal PR
Kossi-stack/Mobile_Version_Skeleton pull request #13
Opened 2021-08-04 22:07 UTC by Kossi-stack

**This project is a pair programming and we did a pop-up window with javascript .**

These are the following requirements for the project.

 - When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
 - When the user clicks (or taps) the close (X) button, the popup disappears.

2021-08-04 22:22 UTC, carlos-ssh requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-04 22:22 UTC, carlos-ssh commented on popup.js
> +  // Popup menu variables////////////////////
[OPTIONAL]
**Keep your project professional:**
- Remove commented lines.

2021-08-04 22:22 UTC, carlos-ssh commented on style.css
- **Kindly fix the style of your project isn't centered.**
![Screen Shot 2021-08-04 at 17 17 58](https://user-images.githubusercontent.com/22258274/128262691-5f06bcda-1a8a-490f-91cd-1766231bd221.png)

- Remove the exceeded  "X".
![Screen Shot 2021-08-04 at 17 20 04](https://user-images.githubusercontent.com/22258274/128262763-2b4ebe77-4b30-40f3-8d10-9f01272865d4.png)

2021-08-05 07:24 UTC, bellom approved these changes
## Hi Team 👏  

**Great work making all the necessary corrections from the previous review.**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-05 07:24 UTC, bellom commented on index.html
> +  <div class="mobile-2"></div>-->
It’s better to delete commented code. If you need to review a previous version of your code, use git history.

I trust you can do this before merging.

2021-08-05 07:36 UTC, merged